version: "3.9"

services:
  app:
    build: .
    container_name: datura-app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    container_name: datura-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    container_name: datura-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: datura
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
